dist: xenial
language: go
os: linux

go:
  - "1.13.x"
  - "1.14.x"
  - master

cache:
  directories:
    - .bin/

jobs:
  fast_finish: true
  allow_failures:
    - go: master

script: make tools lint test
