version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    working_directory: ~/go/src/xelon-sdk-go

    steps:
      - checkout

      - run:
          name: "Lint code with golangci-lint"
          command: |
            make tools lint

      - run:
          name: "Run unit tests and calculate coverage"
          command: |
            make test
